# Multi-stage build for React SPA
FROM node:18-alpine AS builder

WORKDIR /app

# Build arguments for React environment variables
ARG REACT_APP_GOOGLE_BOOKS_API_KEY
ARG REACT_APP_FIREBASE_MEASUREMENT_ID
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_STRIPE_PUBLISHABLE_KEY
ARG REACT_APP_STRIPE_BASIC_PRICE_ID
ARG REACT_APP_BOOK_CHAT_FUNCTION_URL

# Expose build args as env vars for react-scripts build
ENV REACT_APP_GOOGLE_BOOKS_API_KEY=$REACT_APP_GOOGLE_BOOKS_API_KEY \
    REACT_APP_FIREBASE_MEASUREMENT_ID=$REACT_APP_FIREBASE_MEASUREMENT_ID \
    REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY \
    REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN \
    REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID \
    REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET \
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID \
    REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID \
    REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY \
    REACT_APP_STRIPE_BASIC_PRICE_ID=$REACT_APP_STRIPE_BASIC_PRICE_ID \
    REACT_APP_BOOK_CHAT_FUNCTION_URL=$REACT_APP_BOOK_CHAT_FUNCTION_URL \
    CI=false \
    NODE_OPTIONS="--max-old-space-size=4096"

COPY package*.json ./

RUN npm ci --legacy-peer-deps || npm install --legacy-peer-deps

COPY . .

RUN npm run build

# Runtime stage: Nginx
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
